export const DEFAULT_STATE_FF_EF = {
  isFetching: false,
  isError: false,
  response: {},
};
export const PREFERENCE = "PREFERENCE";
export const CURRENT_TAB_INDEX = "CURRENT_TAB_INDEX";
export const ENV_UPDATE = "ENV_UPDATE";
export const QUIZ_REATTEMPT = "QUIZ_REATTEMPT";
export const QUIZ_RESUME = "QUIZ_RESUME";
export const QUIZ_SOLUTION = "QUIZ_SOLUTION";
export const QUIZ_START = "QUIZ_START";
export const QUIZ_START_TIMER = "QUIZ_START_TIMER";
export const MOCKTEST_STATUS = "MOCKTEST_STATUS";
export const MOCKTEST_REATTEMPT = "MOCKTEST_REATTEMPT";
export const MOCKTEST_START = "MOCKTEST_START";
export const MOCKTEST_START_TIMER = "MOCKTEST_START_TIMER";
export const IS_NEW_USER = "IS_NEW_USER";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_IMAGE_UPDATE = "PROFILE_IMAGE_UPDATE";
export const PREFERENCE_UPDATE = "PREFERENCE_UPDATE";
export const DISABLE_PREFERENCE = "DISABLE_PREFERENCE";
export const UPDATE_COURSE_DETAILS = "UPDATE_COURSE_DETAILS";
export const CURRENT_COURSE = "CURRENT_COURSE";
export const CURRENT_PAGE_ROUTING = "CURRENT_PAGE_ROUTING";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const ENV_ENDPOINT = "ENV_ENDPOINT";
export const ENV_REMOTECONFIG = "ENV_REMOTECONFIG";
export const BANNER_UPDATE = "BANNER_UPDATE";
export const ACTIVE_MENU = "ACTIVE_MENU"
